services:

  frontend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - "15678:5678" # debugger

  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "25678:5678" # debugger
